### ISSUE TITLE
Blad w Pliku

### ISSUE THREAD

**Issue by zelisce** [IndianBartonka/Bedrock-Polish-Wiki#1]
W pliku "vanilla/scripting/README.MD" jest błąd. Opisuje on kodowanie które jest tylko dostępne dla BDS'ow. Jest to błędne, ponieważ w BDSach się używa Addonow które są taksamo dostępne na świecie jak na BDSie i Realmach

**Comment by IndianBartonka** [comment]
Realm używa BDS a BDS to częśc klienta Vanilal co jest opisane w innym pliku, ale warto może o tym wspomnieć i tu
